-- CreateEnum
CREATE TYPE "GroupType" AS ENUM ('STOKVEL', 'SAVINGS_CLUB', 'LENDING_POOL', 'EMERGENCY_FUND', 'INVESTMENT_CLUB', 'COOPERATIVE', 'BURIAL_SOCIETY', 'OTHER');

-- CreateEnum
CREATE TYPE "GroupStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DISSOLVED');

-- CreateEnum
CREATE TYPE "MemberStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'WITHDRAWN');

-- CreateEnum
CREATE TYPE "MeetingStatus" AS ENUM ('SCHEDULED', 'HELD', 'CANCELLED', 'POSTPONED');

-- CreateEnum
CREATE TYPE "ContributionStatus" AS ENUM ('RECORDED', 'VERIFIED', 'DISPUTED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "WithdrawalStatus" AS ENUM ('REQUESTED', 'APPROVED', 'PAID', 'REJECTED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "LoanStatus" AS ENUM ('PENDING', 'APPROVED', 'ACTIVE', 'COMPLETED', 'DEFAULTED', 'CANCELLED');
